### ISSUE TITLE
[1.9.7] Markdown Header ID ignored in subdirectories

### ISSUE THREAD

**Issue by eseiler** [doxygen/doxygen#10056]
**Describe the bug**
Have a directory tree like this:
```
.
├── Doxyfile
├── file.hpp
└── subfolder
    └── file.md
```

With `file.md`:
```
# A file {#md_file}

Hello World.
```

With `file.hpp`:
```cpp
//!\brief A struct. Refer to \ref md_file. Refer to \ref md_subfolder_2file.
struct S
{
    //!\brief Some int.
    int x;
};
```

In `1.9.6`, `\ref md_file` properly resolved. In `1.9.7`, it cannot be resolved. However, in `1.9.7` `\ref md_subfolder_2file` works.

The `Doxyfile` is the default config for `1.9.7`, with
```
GENERATE_LATEX         = NO
INPUT                  = . subfolder
```

**Expected behavior**
I'd expect it to work like in `1.9.6` and indicated in the [documentation](https://www.doxygen.nl/manual/markdown.html#md_header_id).

**To Reproduce**
[example.tar.gz](https://github.com/doxygen/doxygen/files/11515614/example.tar.gz)

**Version**
`1.9.7 (6a2ce4d18b5af1ca501bcf585e4c8e2b2b353b0f)`

**Comment by albert-github** [comment]
Problem looks like to be introduced with:
```
Commit: e0c9d9c4187ffcd90cf56e469f94615ae9fd072c [e0c9d9c]
Date: Friday, March 17, 2023 9:15:44 PM

issue #9254: Markdown page subpage and treeview
```

**Comment by albert-github** [comment]
I looked in the `commentscan.l` and as far as I can see the rule:
```
<PageDocArg1>[^\n]*"\\ilinebr @ianchor"\{[^\]\n]*\}{B}{FILE}
```
handles the `@ianchor` part as the page label but forgets about the original page anchor and name so the reference to the `{#...}` label.

I don't directly see a solution so that the current problem is solved but also the treeview problem from #9254
@doxygen do you see a solution?

**Comment by doxygen** [comment]
@eseiler Please verify if the referenced commit fixes the problem for you.

**Comment by joergpichler** [comment]
@doxygen It is fixed for me with the mentioned commit.

**Comment by eseiler** [comment]
Fixed, thank you!

**Comment by albert-github** [comment]
With the original #9254 I still see a small problem (was also a problem with 1.9.7), tested with 1.9.8 (https://github.com/doxygen/doxygen/commit/0ea6a2376f93d1bde432429f58666884e018a07a). When we have:
**main.md**
```
\page main Main
main content

- \subpage main-sub-inner "main sub inner link"
- \subpage main-sub-outer "main sub outer link"

\page main-sub-inner Sub Inner

main-sub-inner content
```
and  **main-sub-outer.md**
```
\noop some extra text so the page command is not the first command


\page main-sub-outer Sub Outer

main-sub-outer content
```
we get as output:
![image](https://github.com/doxygen/doxygen/assets/5223533/9969eef7-9f14-4961-bc6c-ba49ca901b55)


so we see here in the treeview and in the related pages `main-sub-outer`  whilst I would have expected `Sub Outer`

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/11553617/example.tar.gz)
