### ISSUE TITLE
Unable to get property 'style' of undefined or null reference

### ISSUE THREAD

**Issue by Dowan35** [doxygen/doxygen#11006]
Hello, when running doxygen.exe 1.11 with a doxyfile.dox 1.11 too i have this error message spawning randomly and not consistently in the generated .chm when oppening sections.

![Screenshot 2024-07-17 094254](https://github.com/user-attachments/assets/85628fcb-07d6-40c4-a9fa-7370003bd5fb)

The doxyfile use hhc.exe 1.31 to create the chm and I have no problems when using doxygen.exe 1.9.3 is not causing this issue but this version does not support tag 'INPUT_FILE_ENCODING' that fix the issues of the special characters 'é' 'è' replaced with '?' elements in the Namespaces and Classes auto generated doc from a .cs project. (tried with UTf8, first part is ok, second part  (namespaces and classes auto generated) does not accept special characters, this is the opposite when choosing ISO-8859-1)

So that is why I need a working 1.11 version, tried to replace the resize.js as in #11000 but I cant compile the doxygen project on my machine (no admin rights).

The issue is still here when changing DISABLE_INDEX and GENERATE_TREEVIEW to yes or no, I see that in v1.11 everytime I open a book/page, the right scroll bar blink and the displayed page goes back to the top, something that does not append in v 1.9.3, might be a problem when displaying the content, the issue does not comes from my personal content.

Thanks for your help.

UPDATE; "fixed" by executing with doxygen v 1.10 instead of 1.11

**Comment by Dowan35** [comment]
I dont have anymore the .js error when compiling with doxygen 1.10. Thanks for your answer. Yes chm is an ooold thing but there are some people here that like using old things.

**Comment by albert-github** [comment]
So the problem is stell present with the 1.11.0 version.

@doxygen
We currently have a jquery.js that is the minimized version of the jquery official together with some tools. 
I did a small experiment with this doxygen version where I added a number of newlines so the the line does not overflow anymore.
There also exists on the jquery website a "normal" / readable version of jquery.js and this version is a little bit bigger and also contains some comments. This version does work as well. 
Probably this "normal" version is loading a bit slower so not so good for non chm use.

Would it be possible to supply in the deps directory also a "doxygen" jquery version based on the "normal" jquery.js so that this file can be used and loaded when `GENERATE_HTMLHELP = YES`.
(just providing the file would be sufficient, I can have a look at the the changes necessary for `GENERATE_HTMLHELP = YES`).

**Comment by albert-github** [comment]
According to my quick test it did work.
- probably the `--lline-break` setting can even a bit higher (I suspect the the limit is around the 32k so e.g. 10k or 20k should be OK as well).
- the provided `jquery.js.zip`  was missing the addons but for my test it didn't matter.

having this type of `jquery.js` would be better as we don't have to have some special constructs for `GENERATE_HTMLHELP`

**Comment by doxygen** [comment]
> the provided jquery.js.zip was missing the addons but for my test it didn't matter.

Which missing addons are you referring to? The zipped `jquery.js` should include all the extras such as `jquery.ui.*` and `smartmenus`. The copyright for each is shown in the file.

**Comment by albert-github** [comment]
In the "old" jquery.js the addons were at the the end and quite distinctly visible. I see that they are in the zip file as well, but less distinct, so I didn't see them and they are not missing.

**Comment by doxygen** [comment]
@Dowan35 Please verify if the referenced commit fixes the problem for you. Do not close the issue, this will be done automatically when the next official release becomes available.

**Comment by albert-github** [comment]
@doxygen 

I have problems with the provided jquery.js (and tabs.css) in the repository as it gives an error analogous to the initial one but for line 33 position 395.
I "resplit" the file on the `}` like I initially tested (needed to join a few strings onto one line) but this didn't work either.

The jquery.js supplied earlier for testing (in https://github.com/doxygen/doxygen/issues/11006#issuecomment-2236584443) did work (and still looks like to works).

**Comment by doxygen** [comment]
@albert-github problem with the file I posted is that it was not working in a normal browser (at least when `GENERATE_TREEVIEW` was enabled).

Can you try [this version](https://github.com/user-attachments/files/16313026/jquery.js.zip) with max length set to 250 like before.

**Comment by albert-github** [comment]
Unfortunately similar problem, line 134 char 167

The problem I encounter is with the doxygen chm manual, more specific with the embedded examples there.
The remark `GENERATE_TREEVIEW=YES` is here not in place but I also saw `HTML_DYNAMIC_MENUS` having the wrong value for chm (also wrong is `HTML_COPY_CLIPBOARD`), so I now set `HTML_DYNAMIC_MENUS` to `NO` in the examples and the version posted as commit `4ff9550` and this version (https://github.com/doxygen/doxygen/issues/11006#issuecomment-2239263018) work. So it might also have been a bit of consequential damage.

It is a bit strange that the "250" version (where `HTML_DYNAMIC_MENUS`  had the wrong value) did work.

I already intended to change the generation of the doxygen chm documentation to a have proper setup (and also the html version so that there everywhere "TOGGLE" is used).

@Dowan35 still it would be good when you could test the version in the repository and the version provided with https://github.com/doxygen/doxygen/issues/11006#issuecomment-2239263018 as otherwise the problem might be lingering around a bit.

**Comment by albert-github** [comment]
Regarding the (see https://github.com/doxygen/doxygen/issues/11006#issuecomment-2239575999):
> I already intended to change the generation of the doxygen chm documentation to a have proper setup (and also the html version so that there everywhere "TOGGLE" is used

I've just pushed a proposed patch, pull request #11019

**Comment by albert-github** [comment]
The mentioned PR #11019  has been integrated in master on GitHub

**Comment by albert-github** [comment]
I think all problems mentioned here have been solved (please don't close the issue as this will be done at the moment of an official release)

**Comment by paule32** [comment]
according to the Problem, I started a little HTML WebViewer Project, that make it possible to use CHM Files with modern Engine - that is Edge based. It could be better, as stuck into the Code of doxygen, instead providing a modern Application that can handle new stuff ...

**Comment by maettu-this** [comment]
The latest version 1.13.2 unfortunately still shows this issue, no matter whether with or without `HTML_DYNAMIC_MENUS`:

![Image](https://github.com/user-attachments/assets/931c3662-1290-4c9c-8372-6ebf8ce04e91)

Could be related to the length of the content (Zeichen: 395).

Please reopen the issue (I do not have permissions to do so). For the moment, I downgrade to Doxygen 1.10.0 where this issue is not apparent.

**Comment by albert-github** [comment]
Strange, what is the size of the jquery.js you used (I expect it to be 176782 bytes)

**Comment by maettu-this** [comment]
Oh, I have no clue what get's generated in dertail. It happens when I click the `Topics` or `File` in the menu of a generated `.chm` inside the MS HTML Help Viewer. Is there a way I can debug this?

PS: I am fully aware the MS HTML Help Viewer is way out of date. However, we are regularly evaluating alternatives and none so far seems to give the features and compactness of the old beast.

**Comment by albert-github** [comment]
I don't know a way of debugging this.
There will be a html directory generated and in this directory are the generated files (also jquery.js), maybe you can publish these files?

**Comment by maettu-this** [comment]
I have been able to condense the issue into a repro sample:

![Image](https://github.com/user-attachments/assets/b1bdcaf5-a875-40f7-984b-7b31beac309a)

See attached file for working directory content:

[Issue 11006 Repro Sample.zip](https://github.com/user-attachments/files/20185702/Issue.11006.Repro.Sample.zip)

To reproduce from .zip:

1. Open `doxydoc.chm`
2. Click `Topics` and `Files` until the show error message appears

To reproduce from source:

1. Remove `/_Doxygen` and `doxydoc.chm`
2. Run `doxygen config.doxy`
3. Proceed as described above

The exception is triggered at line 33 of `jquery.js` here:
```
S.readyException=function(e){C.setTimeout(function(){throw e})}
                                                     ^      
```

**Comment by albert-github** [comment]
I'm not able to reproduce the issue on my Windows 10 system (US-EN settings)
I didn't see differences in the generated HTML (except for the text with the generation date and time). One remarkable thing was that my chm file was 4 bytes smaller...

**Comment by maettu-this** [comment]
Strange indeed. At home, on my Win10 machine (CH-DE) I cannot trigger the exception either. However, I cannot even see the [Main Page] [Topics] [Files] menu. Could you see the menu?

Tomorrow, I'll ask a collegue to try on a US-EN configured Win10 or Win11 machine. I'll let you know.

**Comment by maettu-this** [comment]
Alright, here is additional info:

We all use HTML Help Control Version 10.0, in English or German:

![Image](https://github.com/user-attachments/assets/08a65ffb-41f8-461f-965c-fd10f4b4a203)

Win11 en-US throws:

![Image](https://github.com/user-attachments/assets/c1dc1a3c-d8d5-4154-8c39-2895f5140c47)

**Win10 en-US does not throw!**

**Comment by maettu-this** [comment]
@Dowan35, you could add your Windows version to help further analysis of this issue. Seems the issue only occurs on Win11.

**Comment by albert-github** [comment]
I'm not sure which version of HTML Help I'm running as I only have the executable and some dlls (it must in fact be the last one released), but seen the experience mentioned the HTML Help compiler version should not be the issue here.

Regarding the question "However, I cannot even see the [Main Page] [Topics] [Files] menu. Could you see the menu?":
- YES I can see the menu in the same way as shown in the image in https://github.com/doxygen/doxygen/issues/11006#issuecomment-2882945169

**Comment by maettu-this** [comment]
You find the version info here:

![Image](https://github.com/user-attachments/assets/f0902d1b-ec8d-469b-a48c-47f5945db0ae)

Summarizing based on the information I have:

- Viewer version is not the root cause.
- Language is not the root cause.
- **Something in Win11 is the root cause.**

**Comment by albert-github** [comment]
I cannot imagine that that is the case as at that moment the xml lint checker I use should have given an error as well and it doesn't.
