### ISSUE TITLE
Struct inside groups are missing in the left menu

### ISSUE THREAD

**Issue by parmi93** [doxygen/doxygen#11650]
```c
/**
 * @file temp.h
 * 
 * @defgroup my_group My group
 * @{
 */

 /**
  * @brief My define brief
  */
#define MY_DEFINE (1)

/**
 * @brief My enum brief
 */
typedef enum {
    ENUM1, ///< Enum1
    ENUM2  ///< Enum2
} my_enum_t;

/**
 * @brief My struct brief
 */
typedef struct 
{
    int a; ///< a description
    int b; ///< a description
} my_struct;

/**
 * @brief My handle
 */
typedef void *handle_h;

/**
 * @brief My function brief
 * 
 * @param[in] my_param My parameter.
 * @retval true Successful.
 * @retval false Fail
 */
bool my_function(int my_param);

/** 
 * @}
 */

```

![Image](https://github.com/user-attachments/assets/0cf1a945-4aea-4be7-a8dc-f7cd34d78b42)

Attaching sample project to reproduce the problem:
[doxygen_bug.zip](https://github.com/user-attachments/files/21037144/doxygen_bug.zip)

**Comment by albert-github** [comment]
In your layout file you have:
```
<tab type="classes" visible="no" title="">
```
and thus classes are not show in the treeview.
structs are a type of classes as well and thus not shown in the treeview either.

I think the issue is usage.

**Comment by parmi93** [comment]
I set `classes` visibility to `no` on purpose, to hide them from the overview section and leave them visible only in the definition section.
What I want to do is hide the overview section completely, setting `visible="no"` for `<defines>`, `<enums>`, `<typedefs>` and `<classes>`, and leaving only the detailed documentation of the various members, everything works as I expected, except for the structs which are not visible in the treeview.

**Comment by albert-github** [comment]
Like written before structs, nowadays, are very similar to classes and are handled in the same way and as the visibility of the classes is set to no this also implies that structs are not visible. When setting the classes to visible you wil see that structs and classes both are visible and are both in the same classes lists.

**Comment by parmi93** [comment]
I understand that classes and structs are treated the same by Doxygen, but that's not the problem.

What I'm trying to do is hide the structs/classes from the overview and leave them visible only in the detailed section, which I can do without problems, but I don't want the structs/classes to be hidden from the treeview

This is the relevant part of my layout:
```xml
<doxygenlayout version="2.0">
    <group>
        <memberdecl>                       <!-- Starts overview section -->
            <defines visible="no" title=""/>    <!-- Hides macros from overview -->
            <enums visible="no" title=""/>      <!-- Hides enums from overview -->
            <typedefs visible="no" title=""/>   <!-- Hides typedefs from overview -->
            <classes visible="no" title=""/>    <!-- Hide structs/classes from overview and treeview (why?) -->
            <variables visible="no" title=""/>  <!-- Hides variables from overview -->
            <functions visible="no" title=""/>  <!-- Hides functions from overview -->
        </memberdecl>                      <!-- Ends overview section -->

        <memberdef>                        <!-- Starts detailed section -->
            <defines visible="yes" title=""/>       <!-- Makes macros visible in the detailed section and treeview -->
            <enums visible="yes" title=""/>         <!-- Makes enums visible in the detailed section and treeview  -->
            <typedefs visible="yes" title=""/>      <!-- Makes typedefs visible in the detailed section and treeview  -->
            <inlineclasses visible="yes" title=""/> <!-- Makes structs/classes visible in the detailed section but NOT in treeview -->
            <variables visible="yes" title=""/>     <!-- Makes variables visible in the detailed section and treeview -->
            <functions visible="yes" title=""/>     <!-- Makes functions visible in the detailed section and treeview  -->
        </memberdef>                       <!-- Ends detailed section -->
    </group>
</doxygenlayout>
```

So the question is why `<classes visible="no" title=""/>` hides classes/structs from the treeview too?

**Comment by parmi93** [comment]
Experimenting with doxygen layout I concluded that Doxygen's behavior regarding treeview generation is that if the attribute `visible="yes"` for any `<element>` of `<memberdef>` then that `<element>` is visible in the treeview, except for `<inlineclasses>`


I think to solve the problem the `<classes>` element should be supported in `<memberdef>` too, or `<inlineclasses>` should be made visible in the treeview as well.

**Comment by albert-github** [comment]
>  but I don't want the structs/classes to be hidden from the treeview

Well what will be present that you don't like when you set in the top part the classes part to visible?

**Comment by parmi93** [comment]
> Well what will be present that you don't like when you set in the top part the classes part to visible?

I will have an overview of all structs at the top of all pages (groups) which clutters the documentation, and contains practically no useful information, by completely removing the overview section the documentation is clearer, cleaner and easier to navigate.

In my opinion the overview at the top of the pages is (almost) a duplication of the treeview, it adds **almost** nothing more than the information that the treeview already provides, to get information about a struct, enum, function etc.. the User can simply click on the relevant element in the treeview.
I think the overview makes the documentation redundant.

**Comment by albert-github** [comment]
I must be missing something or I don't understand what is missing / superfluous.
> I will have an overview of all structs at the top of all pages (groups) which clutters the documentation, and contains practically no useful information, by completely removing the overview section the documentation is clearer, cleaner and easier to navigate.

Can you show an image with and without classes set to visible and indicate what is superfluous in the with cxallsses visible?

**Comment by parmi93** [comment]
```c
/**
 * @file temp.h
 * 
 * @defgroup my_group My group
 * @{
 */

/**
 * @brief My struct brief
 *
 * Detailed description of this struct
 */
typedef struct 
{
    int a; ///< a description
    int b; ///< a description
} my_struct;

/** 
 * @}
 */
```

![Image](https://github.com/user-attachments/assets/9c12bd47-621b-46b6-9b8c-6c7fe3b655fc)

**Comment by albert-github** [comment]
OK I see, looks like a briefdescription that has to be set to not visible.
For completeness please make a zip with the source file, the used settings / configuration file and possible extra files layout) you used. Looks a bit redundant but at that moment we are sure we are both using the same information.

**Comment by parmi93** [comment]
[doxygen_bug.zip](https://github.com/user-attachments/files/21056649/doxygen_bug.zip)

p.s.
another problem I noticed is that the `title` attribute of `<inlineclasses>` has no effect

**Comment by albert-github** [comment]
I can now see what you want, have to investigate...

**Comment by parmi93** [comment]
Just to know, was this Issue closed because it was fixed or because it was decided that it shouldn't be implemented?

**Comment by albert-github** [comment]
Looks like it is closed because of the `usage` tag, please check with the new release of doxygen whether or not it is fixed.
When not fixed it should be reopened (and we have to remove the `usage` tag, and see what can / should be done).

**Comment by parmi93** [comment]
The new version (v1.15.0) does not change anything in regard of this Issue.
