### ISSUE TITLE
ingroup does not allow muliple groupnames (Origin: bugzilla #572042)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3280]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-02-16 17:23:57 +0000, Mai-Kee Reiss wrote:

> Hi Dimitri,
> 
> this may be fixed for C# or class members in general. But it still does not
> work for plain C. (Last checked with 1.5.8 from Dec, 27th, 2008).
> 
> The documentation tells "\ingroup (<groupname> [<groupname> <groupname>]) ...
> it will be added to the group or groups identified by <groupname>." 
> So, multiple Groups are allowed. Basically.
> 
> The documentation also tells something like "having multiple groups for a link
> target will confuse the output". (not found the place in the .chm, but it's
> there). 
> Well, in this special case, we are talking about multiple sources which are
> linking to the same index. Then linking to the next index, and so on.
> 
> Imagine, I have a function SetRadioPowerState(). I would like to add this to
> groups: Radio, PowerSaving. While my function SuspendTerminal() should be
> member of BoardSupportPackage, Interactive, PowerSaving. So the User can find
> both functions multiple times linked from the directory and the groups list.
> 
> I think, this should also be able for plain-C code, or?
> 
> 
> 
> Other information:
> You could reopen Bug 173110 and disregard this new one.
> In fact, I added the same comment there. But then I found that i can not reopen the bug myself.

**Comment by szanni** [comment]
I can confirm this bug is still found in version `1.9.3`.

Documenting something in `C` as:
```c
/**
 * @ingroup g1 g2
 * @memberof bar
 */
void func();
```
Will give the error message:
> `warning: Member func found in multiple @ingroup groups! The member will be put in group g2, and not in group g1`

Whereas the docs clearly state that things can belong to multiple groups:
> `\ingroup (<groupname> [<groupname> <groupname>])`

**Comment by doxygen** [comment]
The [grouping](https://www.doxygen.nl/manual/grouping.html) page of the manual says:

> Note that compound entities (like classes, files and namespaces) can be put into multiple groups, but members (like variable, functions, typedefs and enums) can only be a member of one group (this restriction is in place to avoid ambiguous linking targets in case a member is not documented in the context of its class, namespace or file, but only visible as part of a group).

So it is a documented limitation.

**Comment by albert-github** [comment]
I agree with the comment https://github.com/doxygen/doxygen/issues/3280#issuecomment-1139377273 but it might be better to specify the limitation with the `\ingroup` as well.

I've just pushed a proposed patch, pull request #9357


I extended the example a little bit to 3 groups and at that moment we get the warning:
```
.../aa.h:16: warning: Member func found in multiple @ingroup groups! The member will be put in group g2, and not in group g1
.../aa.h:16: warning: Member func found in multiple @ingroup groups! The member will be put in group g3, and not in group g2
```
when we specify for the function:
```
@ingroup g1 g2 g3
```
This might be a bit confusing (2 warnings where the second warning overrules again the first).

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/8785400/example.tar.gz)

**Comment by albert-github** [comment]
Documentation update (#9357) has been integrated in master on GitHub.
I leave the issue open as maybe we should do something (in the future) about the limitation and the double warning in case of 3 or more groups with the same `\ingroup` command.

**Comment by szanni** [comment]
> Documentation update (#9357) has been integrated in master on GitHub. I leave the issue open as maybe we should do something (in the future) about the limitation and the double warning in case of 3 or more groups with the same `\ingroup` command.

Good. The comment definitely helps.

The behavior and/or wording is still wrong IMO with regards to C though. Freestanding functions that are not _members_ of anything should IMO be treated similar to a class. Classifying and treating them as _members_ is incorrect.
