### ISSUE TITLE
Out-of-line documentation of scoped enums

### ISSUE THREAD

**Issue by olafmandel** [doxygen/doxygen#6471]
Documentation of scoped enums (also: C++11 enums, `enum class` or `enum struct`) does not work as expected: the table of enumerators is missing from the documentation and thus any link to the enumerator documentation is also missing.

Self-contained example (including buglist):

    // Tested with doxygen 1.8.13 & 1.8.14 and default Doxyfile

    enum EnumA { a, z };
    enum class EnumB { a, z };

    namespace Namespace {
        enum EnumC { a, z };
        enum class EnumD { a, z };
    } // Namespace

    struct Class {
        enum EnumE { a, z };
        enum class EnumF { a, z };
    };

    /** \file
     *  \brief Some file
     *  \bug Entries from #EnumB and #Namespace::EnumD are missing in bug list
     */
    /** \enum EnumA
     *  \brief A working unscoped enum in file scope
     */
    /** \var a
     *  \brief Beginning of #EnumA
     */
    /** \var z
     *  \brief End of #EnumA
     */
    /** \enum EnumB
     *  \brief A non-working scoped enum in file scope
     *  \bug Enumerators table missing in Type Documentation of #EnumB
     */
    /** \var EnumB::a
     *  \brief Beginning of #EnumB
     *  \warning no uniquely matching class member found for EnumB::a
     */
    /** \var EnumB::z
     *  \brief End of #EnumB
     *  \warning no uniquely matching class member found for EnumB::z
     */
    /** \namespace Namespace
     *  \brief Some namespace
     */
    /** \enum Namespace::EnumC
     *  \brief A working unscoped enum in a namespace
     */
    /** \var Namespace::a
     *  \brief Beginning of #EnumC
     */
    /** \var Namespace::z
     *  \brief End of #EnumC
     */
    /** \enum Namespace::EnumD
     *  \brief A non-working scoped enum in a namespace
     *  \bug Enumerators table missing in Type Documentation of #EnumD
     */
    /** \var Namespace::EnumD::a
     *  \brief Beginning of #EnumD
     *  \warning no uniquely matching class member found for Namespace::EnumD::a
     */
    /** \var Namespace::EnumD::z
     *  \brief End of #EnumD
     *  \warning no uniquely matching class member found for Namespace::EnumD::z
     */
    /** \struct Class
     *  \brief Some struct
     */
    /** \enum Class::EnumE
     *  \brief A working unscoped enum in a class
     */
    /** \var Class::a
     *  \brief Beginning of #EnumE
     */
    /** \var Class::z
     *  \brief End of #EnumE
     */
    /** \enum Class::EnumF
     *  \brief A non-working scoped enum in a namespace
     *  \bug Enumerators table missing in Type Documentation of #EnumF
     */
    /** \var Class::EnumF::a
     *  \brief Beginning of #EnumF
     *  \warning no uniquely matching class member found for Class::EnumF::a
     */
    /** \var Class::EnumF::z
     *  \brief End of #EnumF
     *  \warning no uniquely matching class member found for Class::EnumF::z
     */

**Comment by pinchartl** [comment]
I'm running into the same issue with today's master branch. Documenting the members of an enum class defined within a class (such as EnumF in the above example) out-of-line works fine when omitting the enum name (e.g. \var Class::a) if only one enum has an enumerator with that name, but this breaks as soon as two enums in the same class have enumerators with the same name.

**Comment by albert-github** [comment]
@pinchartl 
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce your problem? Please don't add external links as they might not be persistent.

**Comment by pinchartl** [comment]
Here's a standalone test case. Sorry for not having provided it in the first place.

[scoped-enums.zip](https://github.com/doxygen/doxygen/files/5102299/scoped-enums.zip)

With the two scoped enums in the source file, I get

```
/home/laurent/src/test/doxygen/scoped-enums/main.h:31: warning: no uniquely matching class member found for 
  Class::Enum1::Flag

/home/laurent/src/test/doxygen/scoped-enums/main.h:40: warning: no uniquely matching class member found for 
  Class::Enum2::Flag
```

Replacing ```#define SECOND_ENUM``` with ```#undef SECOND_ENUM```, I get

```
/home/laurent/src/test/doxygen/enum/main.h:31: warning: no matching class member found for 
  Class::Enum1::Flag
```

**Comment by pinchartl** [comment]
@albert-github Do you need anything else, or is the standalone test case enough ?

**Comment by albert-github** [comment]
No need for extra information, the example is clear.

**Comment by pinchartl** [comment]
> I'm running into the same issue with today's master branch ([ea6e16b](https://github.com/doxygen/doxygen/commit/ea6e16bf7f3af2ed8779df553b8fadbf396737fa)). Documenting the members of an enum class defined within a class (such as EnumF in the above example) out-of-line works fine when omitting the enum name (e.g. \var Class::a) if only one enum has an enumerator with that name, but this breaks as soon as two enums in the same class have enumerators with the same name.

I've also noticed today that this isn't limited to scoped enums. Identical enumerator names in different enums stored in different namespaces also exhibit similar issues, with a "no matching class member found" warning. I've attached a test case, which produces

```
/home/laurent/src/test/doxygen/enums/main.h:54: warning: no matching class member found for 
  outer::inner::Enum2::Enum
```

[enums.zip](https://github.com/doxygen/doxygen/files/5725158/enums.zip)

**Comment by doxygen** [comment]
@pinchartl 

I've corrected the documentation for the inner namespace and then it works:

```c++
/**
 * \brief inner
 */
namespace inner {


enum Enum2 {
        Enum,
        EnumUnique2,
};

/**
 * \enum Enum2
 * \brief Enum2
 *
 * \var Enum
 * \brief Enum2::Enum
 *
 * \var EnumUnique2
 * \brief Enum2::EnumUnique2
 */

} /* namespace inner */
```
Since it is not a scoped C++11 style enum, the Enum values are placed in the scope of the inner namespace. So I think this is usage.

**Comment by pinchartl** [comment]
> Since it is not a scoped C++11 style enum, the Enum values are placed in the scope of the inner namespace. So I think this is usage.

You're right, my bad. The issue is still valid with scoped enums, but not with my last example.

**Comment by doxygen** [comment]
I've just committed a change to deal with the original problem submitted by @olafmandel 
Please let me know if it fixes the problem for you.

**Comment by pinchartl** [comment]
There still seems to be an issue if the class that contains scoped enums is declared in a namespace.

```cpp
/**
 * \file main.h
 * \brief Main file
 */

namespace ns {

/**
 * \namespace ns
 * \brief A namespace
 */

class Class
{
public:
	enum class Enum1 {
		Flag,
	};

	enum class Enum2 {
		Flag,
	};
};

/**
 * \class Class
 * \brief A class
 */

/**
 * \enum Class::Enum1
 * \brief A first enum class
 *
 * \var Class::Enum1::Flag
 * \brief A flag of Enum1
 */

/**
 * \enum Class::Enum2
 * \brief A second enum class
 *
 * \var Class::Enum2::Flag
 * \brief A flag of Enum2
 */

} /* namespace */
```

The latest master branch produces

```
/home/laurent/src/test/doxygen/scoped-enums/main.h:34: warning: no uniquely matching class member found for 
  ns::Class::Enum1::Flag

/home/laurent/src/test/doxygen/scoped-enums/main.h:42: warning: no uniquely matching class member found for 
  ns::Class::Enum2::Flag
```

**Comment by olafmandel** [comment]
> 
> 
> I've just committed a change to deal with the original problem submitted by @olafmandel
> Please let me know if it fixes the problem for you.

Commit 9bf76580 fixes my original complaint, but as pinchartl commented: it fails for multiple conflicting scoped enums inside a class inside a namespace.

Oh, and I broke out the side-note about missing entries in the bug list as #8274.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by pinchartl** [comment]
There's still an issue related to scoped enumerations, as described in https://github.com/doxygen/doxygen/issues/6471#issuecomment-750200937. I don't seems to have permission to reopen this issue, should I create a new one ?

**Comment by albert-github** [comment]
@pinchartl Best is indeed to open a new issue.

**Comment by pinchartl** [comment]
> @pinchartl Best is indeed to open a new issue.

Done, https://github.com/doxygen/doxygen/issues/8281
