### ISSUE TITLE
Supress undocumented function warning regression C#

### ISSUE THREAD

**Issue by trovialdo** [doxygen/doxygen#7359]
When one want doxygen to ignore the documentation on a section of the code but still add it to the output we use `//! \{` and `//! \}` as per [Stackoverflow](https://stackoverflow.com/questions/16993250/suppress-doxygen-warning-for-undocumented-member-function-but-leave-synopsis-in).  This works as expected in 1.8.14 but produces a warning in 1.8.16 for C# (**still works fine for C++**).
Side note: I cannot find anything in Doxygen's documentation about this feature or must have missed it.

```
    /// <summary>
    /// My list
    /// </summary>
    /// <typeparam name="T">something</typeparam>
    public class MyList<T> : Collection<T>
    {
#pragma warning disable 1591
        //! \{
        protected virtual void ClearItems()
        {
            base.ClearItems();
        }
        //! \}
#pragma warning restore 1591
    }
```

Warning (1.8.16) `Class1.cs:13: warning: Member ClearItems() (function) of class Demo::MyList is not documented.` due to `WARN_IF_UNDOCUMENTED = YES` which we want to enable.
 
MWE [Example.zip](https://github.com/doxygen/doxygen/files/3785245/Example.zip)

Tested with 1.8.16 (warning) while in 1.8.13 and 1.8.14 there were no warnings. Expected no warnings.

---

(**Use-case**: we want warnings on undocumented functions, parameters, ... and treat warnings as errors. 
When you inherit from a class which is not part of the project itself (let's say a .NET  framework dll, in C++ terms the STD) we do not want to manually copy its documentation in case we inherit from a class and overwrite a function. So even though we use `WARN_IF_UNDOCUMENTED = YES` we still want to be able to silently ignore sections of the code while still have the functions, classes ect in the output (undocumented). So far this is the only way we know how to achieve this (works well).
While it would be nice we do not expect Doxygen to parse the documentation from the assembly (MSIL) like Visual Studio does when you use "Go to definition" which would enable us to use `/// <inheritdoc/>`  instead (albeit see also #7356).

Example of using Visual Studio's "Go to definition":
```
#region Assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\mscorlib.dll
#endregion

using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.InteropServices;

namespace System.Collections.ObjectModel
{
        ...
        //
        // Summary:
        //     Removes all elements from the System.Collections.ObjectModel.Collection`1.
        protected virtual void ClearItems();
         ...
}
```
)

**Comment by albert-github** [comment]
I also see the warning with 1.8.15.
I think that the fact thar originally there was no message was a bug and that either this is fixed as of its own or as a side effect from some problem that has been solved.
This has to be investigated further.

**Comment by trovialdo** [comment]
If this is not the recommended way of achieving our goal i would be happy to change our usage.

**Comment by trovialdo** [comment]
I see this is also still present in 1.8.17, what would be the recommended way to achieve our goal?

**Comment by trovialdo** [comment]
Bump. Still present in 1.8.18.

What would be the recommended way of ignoring documentation on specific functions while having`WARN_IF_UNDOCUMENTED = YES`? Even though it might originally have been a bug if there is no other way to achieve this behavior i think it might be a worthwhile feature to add.

**Comment by trovialdo** [comment]
@albert-github

**Comment by albert-github** [comment]
No progress.
I still think: I think that the fact that originally there was no message was a bug and that either this is fixed as of its own or as a side effect from some problem that has been solved.

I don't see a, quick, solution here.

There  is a very dirty trick (and I don't advise to use it because of possible side effects):
```
ALIASES = inherited_through_msil=&zwj;
```
and:
```
        /// \inherited_through_msil
        protected virtual void ClearItems()
        {
            base.ClearItems();
        }
```
a restriction is that this only works for methods without arguments and no return type.

**Comment by trovialdo** [comment]
Thanks for the reply (i have read it a while ago but just now came to replying), while not the nicest solution if it resolves our problem i would use it. Unfortunately, as you said, it only works for methods without return type which makes it not really usable for us.

**Comment by redtide** [comment]
I use C++ and it would nice to have this implemented as in the stackoverflow example as `\nowarn` or similar.
My specific use case would be a Qt overrided function that without documentation and by using Qt tags, adds already a `Reimplemented from >BaseClassHere<`

**Comment by albert-github** [comment]
@redtide 

- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).

Another solution might be to add (seen the example) the line:
```
EXCLUDE_SYMBOLS = ClearItems
```
to the doxygen settings file.

**Comment by redtide** [comment]
Here the test, the details in the readme file (used as main page).

[doxygen-override-tags.zip](https://github.com/doxygen/doxygen/files/14073927/doxygen-override-tags.zip)

**Comment by albert-github** [comment]
I see that for the function `mousePressEvent` you use a trick : `///< @if @endif`, I think this can be generalized to
```
ALIASES = nowarn="@if @endif"
```
and at that moment it is possible to use the command `@nowarn` with the intended effect and is also a rather clean solution.
Compared to the initial suggestion it looks like it has the effect that there is no extra white space with the brief and detailed description.

**Comment by albert-github** [comment]
I see that this trick only works as of version 1.9.7 and it is really a trick that uses a side effect.
When looking at the debug output produced by the commentscanner (`doxygen -d commentscan`) we see:
```
CommentScanner: .../include/button.hpp:19
input=[
@if @endif
 ]
-----------
CommentScanner: .../include/button.hpp:19
output=[
brief=[line=19
\iline 20 \ilinebr  ]
docs=[line=20
]
inbody=[line=-1
]
]
```
so the sequence `@if @endif` is translated into the internal command sequence `\iline 20 \ilinebr` and this is, currently, not detected as being empty by doxygen. (The sequence was necessary to have correct line numbers in warnings when using `@if` constructs).
I wrote already:
>and this is, currently, not detected as being empty by doxygen.

so in future it might be detected as being an empty brief description again.

@doxygen 
- should we detect the sequence `@if @endif` at the beginning of the brief  description and when this is the only part in the brief description just see the brief description as empty again?
- should we implement a `@nowarn` type of command that sets a flag so that the warning is suppressed for the specific function even when `WARN_IF_UNDOCUMENTED = YES`? 
  It might be that is better to rename the command to `undocumented_brief` so we can also define `undocumented_details` and the general `undocumented` (i.e. brief and details). The `undocumented_details` could be used when there is some information that one would like to see (call graph is a not very convincing example) but that is suppressed as there is no detailed documentation.

**Comment by redtide** [comment]
> * It might be that is better to rename the command to `undocumented_brief` so we can also define `undocumented_details` and the general `undocumented` (i.e. brief and details).

If I can tell my point of view on this and that `undocumented` should replace `nowarn` it sounds confusing, because compared to a `nowarn` (maybe `warn_ignore` or `warn_ignore_this` which points to the variable settings?) it looks like saying "this remains undocumented" which is not true in all cases like in the example, where the tags' "Reimplemented..." is added and be enough as documentation:
the goal is not to not document a part per se but not having a warning for that exception.

**Comment by dkaszews** [comment]
I would also like to see some kind of explicit empty documentation. I use `WARN_IF_UNDOCUMENTED` with `WARN_AS_ERROR` to not forget documenting something, but sometimes a field is so self-explanatory that no documentation is necessary, but you don't want to remove it from documentation either. Prime example are all special member and comparison functions in C++ - I want to show class supports them, but don't want to litter code with useless comments.

I tried the `/// &nbsp;` trick I found on stackoverflow.com, and it almost works except it leaves an empty line below the member. Maybe that could be fixed by the output generators?

**Comment by albert-github** [comment]
@dkaszews 
- fixing the output generators, is not a good idea as the user explicitly asked for a cetrain output (here `&nbsp;`)
- see the proposed pull request: https://github.com/doxygen/doxygen/pull/11861
