### ISSUE TITLE
Incorrect location for enum in XML file

### ISSUE THREAD

**Issue by 1vanK** [doxygen/doxygen#7635]
Src:

```
1 #pragma once
2
3
4 enum AttributeMode
5 {
6     AM_EDIT = 0x0,
7     AM_FILE = 0x1,
8     AM_NET = 0x2,
9 };
```

Generated XML:
```
<location file="Bug.h" line="5" column="1" bodyfile="Bug.h" bodystart="4" bodyend="9"/>
```

Is `line` and `bodystart` swapped?

[Bug.zip](https://github.com/doxygen/doxygen/files/4319488/Bug.zip)

**Comment by albert-github** [comment]
I get also the impression that the line numbers are interchanged. But for the function `fi` this doesn't look like the case.

When looking in `xmlgen.cpp` around line 982 in the function `generateXMLForMember` we see:
```
    t << "        <location file=\""
      << convertToXML(stripFromPath(md->getDefFileName())) << "\" line=\""
      << md->getDefLine() << "\" column=\""
      << md->getDefColumn() << "\"" ;
    if (md->getStartBodyLine()!=-1)
    {
      FileDef *bodyDef = md->getBodyDef();
      if (bodyDef)
      {
        t << " bodyfile=\"" << convertToXML(stripFromPath(bodyDef->absFilePath())) << "\"";
      }
      t << " bodystart=\"" << md->getStartBodyLine() << "\" bodyend=\""
        << md->getEndBodyLine() << "\"";
    }
    if (md->getDeclLine()!=-1)
    {
      t << " declfile=\"" << convertToXML(stripFromPath(md->getDeclFileName())) << "\" declline=\""
        << md->getDeclLine() << "\" declcolumn=\""
        << md->getDeclColumn() << "\"";
    }
    t << "/>" << endl;
```

From the names of the called functions after "line=" and "bodystart=" it looks OK.

Comparing the output with the HTML output there looks like to be some discrepancies.

@doxygen do you have an idea which are the correct values and names in case of XML?
I created a bit of an extended example to show some more situations: [Bug.tar.gz](https://github.com/doxygen/doxygen/files/4319972/Bug.tar.gz)

**Comment by doxygen** [comment]
Please verify if the proposed commit fixes the problem and keep this bug report open. It will be closed when the next official release is ready.

**Comment by albert-github** [comment]
@doxygen I see that in the `Entry` class an item `bodyColumn` has been added and that this is filled in scanner.l, but:
- I don't see any change in respect to XML, output is still identical
- Is the bodyColumn only relevant for the scanner.l (C / C++ / C# etc.) or also for other scanners

**Comment by albert-github** [comment]
I just saw the lines changed for `<CompoundName,ClassVar>{B}*"{"{B}*` and `<Bases>{B}*"{"{B}*` and in the routine `parseCompounds` but apparently they don't kick in for my extended example.

**Comment by albert-github** [comment]
Just came to the conclusion that I used the wrong new executable for my first test.
I think in respect to the `enum` there is a new problem in the HTML / LaTeX / RTF / Docbook / ... (all using same steering code to generate output) output.

The findings from the current test:
- HTML / LaTeX / RTF / Docbook / ... (all using same steering code to generate output)
   - in _bug_8h.html we see for `AttributeMode` that the Definition says in version 1.8.17 is at line 4 (I think correct) and with the patch it is line 5.
  - as a consequence of the above we also see in the _bug_h_source.html the link (dark gray) is on the lines 4 / 5
- XML
  - we don't see here 4 / 5 issue with `AttributeMode` in _bug_8h.xml as we saw in HTML, this looks OK
  - the column number of the definition of `AttributeMode1`  in _bug_8h.xml is now correct (from 20 to 1)
- the question "Is the bodyColumn only relevant for the scanner.l (C / C++ / C# etc.) or also for other scanners" is still valid.

**Comment by doxygen** [comment]
@albert-github the source line was indeed still based on the location of the body, while it should now be based on the location of the definition. I've corrected that now. Please let me know if you see further issues.

**Comment by albert-github** [comment]
Looks like I still see a problem in the HTML (didn't look at the XML).

In the source code we see the highlight for `AttributeMode` at line 4, this is correct:

![src1](https://user-images.githubusercontent.com/5223533/76700030-6f420c00-66b3-11ea-8af7-cfaba3186c1a.jpg)

but in the documentation we see that the reference is still to line 5:

![doc1](https://user-images.githubusercontent.com/5223533/76700045-9d275080-66b3-11ea-9cd7-502b49ae4908.jpg)

**Comment by doxygen** [comment]
@albert-github Indeed. Not easy to get it completely right. I've made more changes to address these issues. Let me know if you see anything that is still not right.

**Comment by albert-github** [comment]
I understand, quite complex situations.
In the cpp file I don't see a problem anymore.

I posed the question:
- Is the bodyColumn only relevant for the scanner.l (C / C++ / C# etc.) or also for other scanners

I think that this is still relevant. I see in the xml output for a Fortran file that the `column=1` in all cases.
An example project:  [example_ftn.tar.gz](https://github.com/doxygen/doxygen/files/4348302/example_ftn.tar.gz)

```
xml/namespacemod__lines.xml:        <location file="aa.f90" line="6" column="1" bodyfile="aa.f90" bodystart="6" bodyend="6"/>
xml/namespacemod__lines.xml:        <location file="aa.f90" line="9" column="1" bodyfile="aa.f90" bodystart="10" bodyend="12"/>
xml/namespacemod__lines.xml:    <location file="aa.f90" line="4" column="1"/>
```
though they should be (in this case either 3 (module) or 10 (mod_lines);  5 (int) or 16 (ivar) ; 5 (subroutine) or 16 (subr). When bodyColumn is defined in e.g. Fortran, its accuracy of course depends on the correct implementation in the used scanner.

The `bodyend` in Fortran is also not 100% correct (although one can discuss about what is the  end i.e the `end` statement or the last executable statement), but I think this is a fortranscanner.l / fortrancode.l problem.
