### ISSUE TITLE
markdown table add extra test to "\copybrief"

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#7911]
Hi, I create an markdown table have a **copybrief** at the end - and get a error:

msgque.h:2781: warning: @copybrief or @copydoc target 'MqErrorC_C_API\</td>' not found
msgque.h:2781: warning: @copybrief or @copydoc target 'MqBufferC_C_API\</td>' not found
msgque.h:2781: warning: @copybrief or @copydoc target 'MqBufferLC_C_API\</td>' not found
msgque.h:2781: warning: @copybrief or @copydoc target 'MqDumpC_C_API\</td>' not found
msgque.h:2781: warning: @copybrief or @copydoc target 'MqLogFileC_C_API\</td>' not found
msgque.h:2781: warning: @copybrief or @copydoc target 'MqC_C_API\</td>' not found
msgque.h:2847: warning: @copybrief or @copydoc target 'MqBufferC_C_API\</td>' not found
msgque.h:2847: warning: @copybrief or @copydoc target 'MqBufferLC_C_API\</td>' not found
msgque.h:2847: warning: @copybrief or @copydoc target 'MqDumpC_C_API\</td>' not found
msgque.h:2847: warning: @copybrief or @copydoc target 'MqLogFileC_C_API\</td>' not found
msgque.h:2847: warning: @copybrief or @copydoc target 'MqC_C_API\</td>' not found
msgque.h:2847: warning: @copybrief or @copydoc target 'MqFactoryC_C_API\</td>' not found

- The problem is that the markdown table add **\</td>** at the **copybrief** target.
- The second example with the extra char "x" at the end works but has this extra char.
- using a *whitespace* after the **copybrief** target does not help.
- the initial RNS{...} is not the problem.

```
/// Object                | description
/// ------                | -----------
/// RNS{Object}          | the object self
/// RNS{ErrorObject}     | \copybrief MqErrorC_C_API
/// RNS{BufferObject}    | \copybrief MqBufferC_C_API
/// RNS{BufferLObject}   | \copybrief MqBufferLC_C_API
/// RNS{DumpObject}      | \copybrief MqDumpC_C_API
/// RNS{LogFileObject}   | \copybrief MqLogFileC_C_API
/// RNS{ContextObject}   | \copybrief MqC_C_API
///
/// Object                | description
/// ------                | -----------
/// RNS{Object}          | the object self
/// RNS{ErrorObject}     | \copybrief MqErrorC_C_API x
/// RNS{BufferObject}    | \copybrief MqBufferC_C_API x
/// RNS{BufferLObject}   | \copybrief MqBufferLC_C_API x
/// RNS{DumpObject}      | \copybrief MqDumpC_C_API x
/// RNS{LogFileObject}   | \copybrief MqLogFileC_C_API x
/// RNS{ContextObject}   | \copybrief MqC_C_API x

```

doxygen -v
1.8.19 (c545a3d4865e14b645f3c02301c89a1b59ff83e1)
![bug_doxygen](https://user-images.githubusercontent.com/27886664/87849880-64f77f00-c8ec-11ea-83ab-1df5af2129e9.png)

**Comment by albert-github** [comment]
With the information provided it is hard to tell why the `\copybrief` does not work. You indicated that the added `</td>` probably is the cause, but with out a good example it is so:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by aotto1968** [comment]
[doxygen_bug.tar.gz](https://github.com/doxygen/doxygen/files/4941492/doxygen_bug.tar.gz)

/doxygen_bug/test.c:7: warning: @copybrief or @copydoc target 'hallo</td>' not found

**Comment by albert-github** [comment]
The given example will never work as the target `hallo` does not exitsts:
```
/// \brief hallo
/// \details this is hallo
void example (int a, int b);
```
the target here is `example`, so either we need:
```
/// \brief hallo
/// \details this is hallo
void allo (int a, int b);
```
or
```
\copybrief example
```
none the less this is not responsible for the real problem.

Some current workarounds are to use (might lead to one or more extra spaces in the output):
```
///  num1       | \copybrief hallo &zwj;
```
or
```
///  num1       | \copybrief hallo &nbsp;
```

Looks like the problem is introduced in version 1.8.17 when some work is done on the line counting (removing artificial `\n`).

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7912

**Comment by aotto1968** [comment]
you are right - the `copybrief hallo` have to be an `copybrief example` but the BUG is still available because of the bug 
it never worked :-)

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.19.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
