### ISSUE TITLE
Direction printed twice with inline parameter documentation

### ISSUE THREAD

**Issue by ailiop** [doxygen/doxygen#8568]
**Describe the bug**
When documenting function parameters inline (e.g., `/**<[in] description */`), the direction (`[in]`, `[out]`, `[in,out]`) gets output both as a direction indicator (in fixed-width font) _and_ as part of the parameter description.

This issue arises with C/C++ source and HTML output.  I have not tested other sources or output formats.

**Expected behavior**
The parameter direction should not appear in the parameter description.  Indeed, this is the behavior I see if I change the inline documentation to a `@param[in]` block.

**Screenshots**
```c
/**
 * Some function.
 */
void my_function (
    int x                    /**<[in] This description includes the direction */
);
```
![problematic output](https://user-images.githubusercontent.com/1577182/119568379-f7826d80-bd9c-11eb-9ffe-34d8f73ae9b0.jpg)

```c
/**
 * Some other function.
 *
 * @param[in] y This description does not include the direction
 */
void my_other_function (
    int y
);
```
![desired output](https://user-images.githubusercontent.com/1577182/119568080-9eb2d500-bd9c-11eb-8634-be3bc21ea789.png)

**To Reproduce**
[mwe-param-dir-desc-output.zip](https://github.com/doxygen/doxygen/files/6542371/mwe-param-dir-desc-output.zip)

**Version**
- OS: Ubuntu 20.04.2 LTS, via Windows Subsystem for Linux version 2 (WSL2)
- Doxygen: 1.8.17 (installed with `apt install doxygen`)

**Comment by albert-github** [comment]
In version 1.8.17 (and 1.8.18) the problem is present, in version 1.8.19 and newer the problem is go.

I think the problem has been solved in the mean time.

**Comment by ailiop** [comment]
I see.  I cannot install version 1.8.19 right now, so I'll close this issue and reopen it if I find that the issue persists after updating (which I very much doubt).

Thank you!

**Comment by albert-github** [comment]
I would not go for version 1.8.19 but for the current released version (at the moment 1.9.1).
