### ISSUE TITLE
Doc build fails with cairo 1.17.6

### ISSUE THREAD

**Issue by antonio-rojas** [doxygen/doxygen#9319]
**Describe the bug**
Building docs with cairo 1.17.6 fails with this error
```
cd /home/antonio/Software/Arch/packages/doxygen/trunk/src/doxygen-Release_1_9_4/build/examples && ../bin/doxygen diagrams.cfg
error: Failed to extract bounding box from generated diagram file /home/antonio/Software/Arch/packages/doxygen/trunk/src/doxygen-Release_1_9_4/build/examples/../latex/examples/diagrams/latex/class_a__coll__graph.pdf
/home/antonio/Software/Arch/packages/doxygen/trunk/src/doxygen-Release_1_9_4/build/examples/../latex/examples/diagrams/latex/class_a__coll__graph.dot:1: error: Problems running dot: exit code=0, command='dot', arguments='"/home/antonio/Software/Arch/packages/doxygen/trunk/src/doxygen-Release_1_9_4/build/examples/../latex/examples/diagrams/latex/class_a__coll__graph.dot" -Tpdf -o "/home/antonio/Software/Arch/packages/doxygen/trunk/src/doxygen-Release_1_9_4/build/examples/../latex/examples/diagrams/latex/class_a__coll__graph.pdf"'

error: Failed to extract bounding box from generated diagram file /home/antonio/Software/Arch/packages/doxygen/trunk/src/doxygen-Release_1_9_4/build/examples/../latex/examples/diagrams/latex/class_a__inherit__graph.pdf
/home/antonio/Software/Arch/packages/doxygen/trunk/src/doxygen-Release_1_9_4/build/examples/../latex/examples/diagrams/latex/class_a__inherit__graph.dot:1: error: Problems running dot: exit code=0, command='dot', arguments='"/home/antonio/Software/Arch/packages/doxygen/trunk/src/doxygen-Release_1_9_4/build/examples/../latex/examples/diagrams/latex/class_a__inherit__graph.dot" -Tpdf -o "/home/antonio/Software/Arch/packages/doxygen/trunk/src/doxygen-Release_1_9_4/build/examples/../latex/examples/diagrams/latex/class_a__inherit__graph.pdf"'
[...]
```
Error goes away after downgrading cairo to 1.17.4. Graphviz is at 3.0.0

**Comment by albert-github** [comment]
- Do you have the `class_a__coll__graph.pdf` as created with cairo 1.17.4 and 1.17.6?

**Comment by albert-github** [comment]
On the page https://cairographics.org/ I didn't find an indication of the version 1.17.6 (latest version was 1.17.4).
I did some research in the cairo repository: https://github.com/freedesktop/cairo (and git clone git://anongit.freedesktop.org/git/cairo) and saw in the file `src/cairo-pdf-surface.c`:
```
eaaa1415a9 (Adrian Johnson      2008-02-20 21:05:23 +1030 7424)                                  "   /MediaBox [ 0 0 %f %f ]\n"
```
so quite old line.
In the doxygen sources I see:
```
f6ed27964 (Dimitri van Heesch    2019-06-15 15:33:48 +0200 127)        if (sscanf(p+bblen,"%d %d %d %d",&x,&y,width,height)!=4)
```
so also a bit an older line.

It looks like the the `sscanf` statement is not correct and that till now we were "lucky", so the file `class_a__coll__graph.pdf`  would be nice to have.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9320, though the `class_a__coll__graph.pdf` as created with cairo 1.17.6 would still be nice to verify with.

**Comment by antonio-rojas** [comment]
The patch doesn't fix the problem for me. Attached are both versions of the PDF

[class_a__coll__graph.bad.pdf](https://github.com/doxygen/doxygen/files/8645609/class_a__coll__graph.bad.pdf)
[class_a__coll__graph.good.pdf](https://github.com/doxygen/doxygen/files/8645610/class_a__coll__graph.good.pdf)

**Comment by antonio-rojas** [comment]
Bisected to https://gitlab.freedesktop.org/cairo/cairo/-/commit/bd514f6b08c1b31a75948fd99c147319e5aa649f

**Comment by albert-github** [comment]
When I look at the differences of the good and the bad pdf file I see that in the bad file is missing the part:
```
2 0 obj
<< /Type /Page % 1
   /Parent 1 0 R
   /MediaBox [ 0 0 160 100 ]
   /Contents 4 0 R
   /Group <<
      /Type /Group
      /S /Transparency
      /I true
      /CS /DeviceRGB
   >>
   /Resources 3 0 R
>>
endobj
```
so my assumption about the size was not correct, but my patch doesn't hurt seen the code from cairo (maybe they should write it as a `%d` and use the `ceil` function in writing.

- is the 1.17.6 version already officially released?
- I think best is to ask advise at the cairo people whether the missing section is a bug or a feature and how it will be possible to get this again into  the pdf file or how this can be calculated based on the information in the pdf file).


The original doxygen example: [example.tar.gz](https://github.com/doxygen/doxygen/files/8646706/example.tar.gz)

Information more suitable for the cairo people:
- used command: `dot class_a__coll__graph.dot" -Tpdf -o class_a__coll__graph.pdf`
- used dot file ([class_a__coll__graph.dot.tar.gz](https://github.com/doxygen/doxygen/files/8646714/class_a__coll__graph.dot.tar.gz)): 
   ```
   digraph "A"
   {
    // LATEX_PDF_SIZE
     edge [fontname="Helvetica",fontsize="10",labelfontname="Helvetica",labelfontsize="10"];
     node [fontname="Helvetica",fontsize="10",shape=record];
     Node1 [label="A",height=0.2,width=0.4,color="black", fillcolor="grey75", style="filled", fontcolor="black",tooltip=" "];
     Node1 -> Node1 [dir="back",color="darkorchid3",fontsize="10",style="dashed",label=" m_self" ];
   }
   ```

**Comment by antonio-rojas** [comment]
> * is the 1.17.6 version already officially released?

Yes,
 https://lists.cairographics.org/archives/cairo/2022-March/029398.html
https://gitlab.freedesktop.org/cairo/cairo/-/releases

> * I think best is to ask advise at the cairo people whether the missing section is a bug or a feature and how it will be possible to get this again into  the pdf file or how this can be calculated based on the information in the pdf file).

From the linked commit, this looks intentional: `/Page` objects are now compressed to a stream by default, so it's no longer possible to just parse the pdf file (and from a quick look I don't see a way to disable this from graphviz). Presumably the needed info is now encoded in the block
```
7 0 obj
<< /Type /ObjStm
   /Length 8 0 R
   /N 1
   /First 4
   /Filter /FlateDecode
>>
stream
x=ÍœÂ àœOqç'Ò¡5iLº7Š~}{Ãùî	gÖ	þ¶:BQ/ÂŒJðd"8d3=5Úîø!?ÆðšÇÉëûö69QBÉ¿ª®Yœ2Á-œ6>!úD-M¹u€÷¢IÎcÁašÿK
6yM»ºùwé2á
endstream
endobj
```

**Comment by albert-github** [comment]
That is well possible, but the main question now arises:
- how can we decode the stream, i.e. what is its internal structure.
- how can we find the relevant stream part

**Comment by albert-github** [comment]
From some searches it looks like the streams are so called `ASCII85` coded streams (see also: https://en.wikipedia.org/wiki/Ascii85).

It looks like https://github.com/judsonx/base85 gives a good starting point for a decoder.
@doxygen what do you think?

**Comment by doxygen** [comment]
@albert-github I think the ASCII85 decode is just to one of the possible filters. The `/FlateDecode` option seems to suggest the binary data is compressed with zlib.compress. See also https://blog.didierstevens.com/2008/05/19/pdf-stream-objects/ and https://stackoverflow.com/questions/11731425/data-extraction-from-filter-flatedecode-pdf-stream-in-php

**Comment by albert-github** [comment]
Indeed the ASCII85 is one of the possible formats and the one used, as far is I can see, is now `/FlateDecode`.
In doxygen the zlib is not used so far I think so this has to be added when we want to go that way (possibly the best way to go anyway).

**Comment by albert-github** [comment]
The code of the format correction (#9320) has been integrated in master on GitHub, the main problem (stream) remains.

**Comment by albert-github** [comment]
@doxygen any comment about using `zlib` or do you have an idea for another solution?

**Comment by doxygen** [comment]
@albert-github Since `zlib` it is needed in a bit of a corner case only, I would prefer if it was possible to configure the dot tool somehow that it does not let `libcairo` compress the PDF, but I didn't find such option so far. A dependency on `zlib` is not a big problem, I already use it for the Windows build and it is pretty standard on Mac and Linux.

**Comment by uleysky** [comment]
The workaround for this problem is following: set the CAIRO_DEBUG_PDF environment variable to a non-empty value.
```bash
CAIRO_DEBUG_PDF="1" doxygen
```
works for me.
The solution could be to use pdfinfo or the poppler API to get the MediaBox.

**Comment by albert-github** [comment]
@uleysky 
Interesting observation!

- Do you get when `CAIRO_DEBUG_PDF` extra information on e.g. the console?
- Is the `CAIRO_DEBUG_PDF` described somewhere?
- could you make a small example of just running `dot` and creating a `pdf` once with and once without the setting of `CAIRO_DEBUG_PDF` and send the both pdf files and the used dot file?

Regarding the alternatives:
- I think the poppler API might be a bit of an overkill and I don't know what extra requirements and license restrictions would apply, though looking at https://github.com/freedesktop/popplerand on gitlab something might be possible. Is there a description of the API?
- The pdinfo might also be an idea only when a Cpp / C implementation of the underlying functions, do you have a reference?

**Comment by uleysky** [comment]
* No. CAIRO_DEBUG_PDF is only for disabling stream compression.
* No, as far as I know. I ran into the problem described here. Found this bug report. Thanks to the information from the @antonio-rojas, I found a potential solution in the cairo code and checked it.
* Empty dot file:
```
graph {}
```
test.pdf without CAIRO_DEBUG_PDF and test_debug.pdf with it.
[test.pdf](https://github.com/doxygen/doxygen/files/9927107/test.pdf)
[test_debug.pdf](https://github.com/doxygen/doxygen/files/9927108/test_debug.pdf)

* A description of the poppler API can be found here: https://poppler.freedesktop.org/api/cpp/. At a cursory glance, it seems that the following functions are needed: poppler::document::load_from_file, poppler::document::create_page (https://poppler.freedesktop.org/api/cpp/classpoppler_1_1document.html) and poppler::page::page_rect (https://poppler.freedesktop.org/api/cpp/classpoppler_1_1page.html). But I didn't check it. I can't say anything about license restrictions.
* pdfinfo is a command-line tool from the poppler suite. Here is a manual https://linux.die.net/man/1/pdfinfo. Output of
```
pdfinfo -box test.pdf
```
```
Producer:        cairo 1.17.6 (https://cairographics.org)
CreationDate:    Thu Nov  3 19:38:46 2022 +10
Custom Metadata: no
Metadata Stream: no
Tagged:          no
UserProperties:  no
Suspects:        no
Form:            none
JavaScript:      no
Pages:           1
Encrypted:       no
Page size:       80 x 80 pts
Page rot:        0
MediaBox:            0.00     0.00    80.00    80.00
CropBox:             0.00     0.00    80.00    80.00
BleedBox:            0.00     0.00    80.00    80.00
TrimBox:             0.00     0.00    80.00    80.00
ArtBox:              0.00     0.00    80.00    80.00
File size:       964 bytes
Optimized:       no
PDF version:     1.7
```

In my opinion, the optimal solution would be to add poppler as an optional dependency, and without it, use pdfinfo. The environment variable option is good as a quick fix, but bad overall. You never know what will change again in the cairo code.

**Comment by albert-github** [comment]
Thanks for the information.
(I like the example, this is really a minimal example, thanks).

The code in Cairo gives:
```
    if (getenv ("CAIRO_DEBUG_PDF") != NULL)
        surface->compress_streams = FALSE;
```

I think the easiest way is that doxygen sets the environment variable `CAIRO_DEBUG_PDF` to `1` when calling `dot`.
- When using poppler we have to get all the dependencies (and probably also be aware of version changes) so this would be a bit an overkill.
- Regarding pdfinfo the output would be easy to parse, though the problem would be whether pdfinfo is easily available on all systems where doxygen is running. I see under windows that it is part of MiKTeX but under Cygwin it looks like one needs poppler (probably also needed for other OS) and I think the later would be an extra burden certainly when using GitHub Actions (as doxygen does).


@doxygen what do you think?

**Comment by albert-github** [comment]
I've just pushed a proposed patch based on setting the environment variable, pull request #9662

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.6.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by computerix** [comment]
Definitely not fixed in doxygen 1.9.6: 1.9.6 does not build in gentoo with cairo 1.17.6 due to the error described above.
The fix https://github.com/doxygen/doxygen/pull/9662 is in the source code, but is not effective:
The generated pdf files still contain coded streams instead of the pdf commands doxygen is looking for.

I wrapped a shell script around dot and checked the environment,
and CAIRO_DEBUG_PDF is *not* set in the environment of the dot calls.

After setting CAIRO_DEBUG_PDF explicitly in my shell wrapper, doxygen builds without problems 
(but without my dot wrapper, the resulting doxygen of course fails at runtime 
when generating documentation with graphs).

**Comment by uleysky** [comment]
@computerix, I wrote a patch with poppler support. Can you try it? It is necessary that poppler be installed in the gentoo with the cxx USE flag. https://pastebin.com/VB9ER0zb

**Comment by computerix** [comment]
Patch applies cleanly, but segfaults in poppler:

`
#0  0x00007f129431f9d9 in poppler::font_info::~font_info() () from /usr/lib64/libpoppler-cpp.so.0
#1  0x00007f1294327bec in poppler::page::~page() () from /usr/lib64/libpoppler-cpp.so.0
#2  0x0000562a343838f4 in DotRunner::readBoundingBox(QCString const&, int*, int*, bool) ()
#3  0x0000562a343849cd in DotRunner::run() ()
#4  0x0000562a34385ec5 in DotWorkerThread::run() ()
#5  0x00007f12862d497f in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/12/libstdc++.so.6
#6  0x00007f12864e5235 in start_thread (arg=<optimized out>) at pthread_create.c:442
#7  0x00007f128655c08c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
`

Failing build step:
`FAILED: html/examples/diagrams/html/index.html latex/examples/diagrams/latex/refman_doc.tex /var/portage/portage/app-doc/doxygen-1.9.6/work/doxygen-1.9.6_build/html/examples/diagrams/html/index.html /var/portage/portage/app-doc/doxygen-1.9.6/work/doxygen-1.9.6_build/latex/examples/diagrams/latex/refman_doc.tex 
cd /var/portage/portage/app-doc/doxygen-1.9.6/work/doxygen-1.9.6_build/examples && /usr/bin/cmake -E make_directory /var/portage/portage/app-doc/doxygen-1.9.6/work/doxygen-1.9.6_build/html/examples/diagrams && /usr/bin/cmake -E make_directory /var/portage/portage/app-doc/doxygen-1.9.6/work/doxygen-1.9.6_build/latex/examples/diagrams && /usr/bin/cmake -E env PROJECT_BINARY_DIR=/var/portage/portage/app-doc/doxygen-1.9.6/work/doxygen-1.9.6_build /var/portage/portage/app-doc/doxygen-1.9.6/work/doxygen-1.9.6_build/bin/doxygen diagrams.cfg && /usr/sbin/python /var/portage/portage/app-doc/doxygen-1.9.6/work/doxygen-1.9.6/examples/strip_example.py < /var/portage/portage/app-doc/doxygen-1.9.6/work/doxygen-1.9.6_build/latex/examples/diagrams/latex/refman.tex > /var/portage/portage/app-doc/doxygen-1.9.6/work/doxygen-1.9.6_build/latex/examples/diagrams/latex/refman_doc.tex
Segmentation fault
`

**Comment by albert-github** [comment]
@uleysky  Would be nice to post the main change of your patch for poppler so it would be possible to see how the fix the general problem in doxygen.
Furthermore a reference to an external source (here a pastebin directory) is no good:
- it might be non persistent (and this your comment would be non-understandable)
- one doesn't know what hides behind such a link.

**Comment by uleysky** [comment]
@albert-github, @computerix, my apologies. This was the first iteration of the patch, it was not supposed to work the first time, so I did not bring it here. The error with the segfault from my inattention is obvious, here is an version that should work.
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 36b93b622..88a7b3fb9 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -22,6 +22,7 @@ option(build_search    "Build external search tools (doxysearch and doxyindexer)
 option(build_doc       "Build user manual (HTML and PDF)" OFF)
 option(build_doc_chm   "Build user manual (CHM)" OFF)
 option(use_sqlite3     "Add support for sqlite3 output [experimental]." OFF)
+option(use_poppler     "Using poppler to find MediaBox." ON)
 if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
     option(use_libc++  "Use libc++ as C++ standard library." ON)
 endif()
@@ -66,6 +67,11 @@ if (use_libclang)
         find_package(LLVM CONFIG REQUIRED)
         find_package(Clang CONFIG REQUIRED)
 endif()
+if (use_poppler)
+	set(poppler    "1" CACHE INTERNAL "used in settings.h")
+	find_path(POPPLER_INCLUDE_DIR poppler-version.h PATH_SUFFIXES poppler/cpp REQUIRED)
+	find_library(POPPLER_LIBRARY libpoppler-cpp.so REQUIRED)
+endif()
 if (build_wizard)
     if (force_qt STREQUAL "Qt6")
         if (CMAKE_SYSTEM MATCHES "Darwin")
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index e9df895ce..e5a1f1ad0 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -30,9 +30,11 @@ CONTENT "#ifndef SETTINGS_H
 #define SETTINGS_H
 #define USE_SQLITE3 ${sqlite3}
 #define USE_LIBCLANG ${clang}
+#define USE_POPPLER ${poppler}
 #define IS_SUPPORTED(x) \\
   ((USE_SQLITE3  && strcmp(\"USE_SQLITE3\",(x))==0)  || \\
    (USE_LIBCLANG && strcmp(\"USE_LIBCLANG\",(x))==0) || \\
+   (USE_POPPLER && strcmp(\"USE_POPPLER\",(x))==0) || \\
   0)
 #endif" )
 set_source_files_properties(${GENERATED_SRC}/settings.h PROPERTIES GENERATED 1)
@@ -384,6 +386,11 @@ if (use_libclang)
     target_compile_definitions(doxygen PRIVATE ${LLVM_DEFINITIONS})
 endif()
 
+if (use_poppler)
+ target_include_directories(doxymain PRIVATE ${POPPLER_INCLUDE_DIR})
+ target_link_libraries(doxymain INTERFACE ${POPPLER_LIBRARY})
+endif()
+
 target_link_libraries(doxygen PRIVATE
     doxymain
     doxycfg
diff --git a/src/dotrunner.cpp b/src/dotrunner.cpp
index d3b2615f4..9a87b8107 100644
--- a/src/dotrunner.cpp
+++ b/src/dotrunner.cpp
@@ -24,6 +24,9 @@
 #include "config.h"
 #include "dir.h"
 #include "doxygen.h"
+#include "poppler-document.h"
+#include "poppler-page.h"
+#include "poppler-rectangle.h"
 
 // the graphicx LaTeX has a limitation of maximum size of 16384
 // To be on the save side we take it a little bit smaller i.e. 150 inch * 72 dpi
@@ -108,6 +111,27 @@ static bool resetPDFSize(const int width,const int height, const QCString &base)
 
 bool DotRunner::readBoundingBox(const QCString &fileName,int *width,int *height,bool isEps)
 {
+#if USE_POPPLER
+  if(!isEps)
+  {
+   poppler::document* document=poppler::document::load_from_file(fileName.str());
+   if(document==nullptr) return FALSE;
+   poppler::page* page=document->create_page(0);
+   if(page==nullptr)
+   {
+    delete document;
+    return FALSE;
+   }
+   poppler::rectf bbox=page->page_rect(poppler::media_box);
+   *width = static_cast<int>(std::ceil(bbox.width()));
+   *height = static_cast<int>(std::ceil(bbox.height()));
+   delete page;
+   delete document;
+   return TRUE;
+  }
+  else
+#endif
+  {
   const char *bb = isEps ? "%%PageBoundingBox:" : "/MediaBox [";
   size_t bblen = strlen(bb);
   FILE *f = Portable::fopen(fileName,"rb");
@@ -139,6 +163,7 @@ bool DotRunner::readBoundingBox(const QCString &fileName,int *width,int *height,
   err("Failed to extract bounding box from generated diagram file %s\n",qPrint(fileName));
   fclose(f);
   return FALSE;
+ }
 }
 
 //---------------------------------------------------------------------------------

```

**Comment by albert-github** [comment]
@uleysky 
I see that you replace the reading of the bounding box by calling some poppler functions, and thus requiring poppler.
I think this solution is not really suitable for doxygen, unless there is a standalone library that would properly read the encrypted stream parts.
I think it would be better to see what the real problem is behind the fact that the `setenv` doesn't work.

Note: in your solution the `#include` should also be protected by means of `#if USE_POPPLER`.

**Comment by uleysky** [comment]
@albert-github, the real problem is that when the CAIRO_DEBUG_PDF variable will be removed from the cairo code, which someone left for debugging, it will be completely useless to look for where and why setenv does not work. I understand that using poppler is not an ideal solution, but the problem with compressed streams in pdf's needs to be solved somehow. Do not use a crutch, which can break at the most inopportune moment.

I can't debug right now, but I'll try to see what's up with setenv in three or four days on my Gentoo system.

>Note: in your solution the #include should also be protected by means of #if USE_POPPLER.

Yes, my mistake, thanks.

**Comment by computerix** [comment]
I tested the patch. It applies cleanly, it builds, and the resulting doxygen runs fine with the default Doxyfile. However, I've a Doxyfile which has most optional features turned on, and doxygen fails with that Doxyfile:
It shows hundreds of the following error messages:

`Running dot for graph 157/157

Patching output file 1/35

error: problems opening map file /home/kk/nta/inf-swt/work/doxygen/doc/html/bigobj_8cpp__incl.map for inclusion in the docs!

If you installed Graphviz/dot after a previous failing run, 
try deleting the output directory and rerun doxygen.
`

The map files do not exist.

Filally, it fails with

`poppler/error: Couldn't open file '/home/kk/nta/inf-swt/work/doxygen/doc/latex/bigobj_8cpp__incl.pdf': No such file or directory.

error: problem writing FIG 0 figure!
`

**Comment by uleysky** [comment]
Can you share your Doxyfile?

**Comment by computerix** [comment]
[https://www.computerix.info/swt/Doxyfile](url)

**Comment by doxygen** [comment]
I've put together a small standalone tool to extract the `/MediaBox` tag that works with both compressed and uncompressed pdfs. Only external dependency is zlib.
Still pretty rough, and assumes compressed parts are always of `/FlateDecode` type, but could service as a starting point to integrate into doxygen.

```c++
#include <iostream>
#include <sstream>
#include <fstream>
#include <iomanip>
#include <vector>
#include <cstring>
#include <cstdio>

#include <zlib.h>

//#define DBG(x) printf x
#define DBG(x) do {} while(0)

static int infate_buffer(const char *source, size_t source_len, std::vector<char> &dest)
{
  constexpr auto CHUNK = 16384;
  int ret;
  unsigned have;
  z_stream strm;
  unsigned char out[CHUNK];

  /* allocate inflate state */
  strm.zalloc = Z_NULL;
  strm.zfree = Z_NULL;
  strm.opaque = Z_NULL;
  strm.avail_in = 0;
  strm.next_in = Z_NULL;
  ret = inflateInit(&strm);
  if (ret != Z_OK)
    return ret;

  size_t source_pos = 0;
  // decompress until end of buffer
  do
  {
    strm.avail_in = source_pos+CHUNK > source_len ? source_len-source_pos : CHUNK;
    if (strm.avail_in == 0) break;
    strm.next_in = (Bytef*)&source[source_pos];

    /* run inflate() on input until output buffer not full */
    do
    {
      strm.avail_out = CHUNK;
      strm.next_out = out;
      ret = inflate(&strm, Z_NO_FLUSH);
      switch (ret) {
        case Z_NEED_DICT:
          ret = Z_DATA_ERROR;     /* and fall through */
        case Z_DATA_ERROR:
        case Z_MEM_ERROR:
          (void)inflateEnd(&strm);
          return ret;
      }
      have = CHUNK - strm.avail_out;
      dest.insert(dest.end(),(char*)out,(char*)out+have);
    } while (strm.avail_out == 0);

    /* done when inflate() says it's done */
  } while (ret != Z_STREAM_END);

  /* clean up and return */
  (void)inflateEnd(&strm);
  return ret == Z_STREAM_END ? Z_OK : Z_DATA_ERROR;
}

int main(int argc,char **argv)
{
  if (argc<2) { printf("Usage %s file.pdf\n",argv[0]); exit(1); }
  std::ifstream f(argv[1],std::ifstream::in | std::ios::binary);
  if (!f.is_open()) { printf("failed to open file %s\n",argv[1]); exit(1); }
  std::stringstream buffer;
  buffer << f.rdbuf();
  std::string contents = buffer.str();

  const std::string mediaBox="/MediaBox [";
  auto showMediaBox = [&mediaBox](const char *s,const char *type)
  {
    int x,y;
    double w,h;
    if (sscanf(s+mediaBox.length(),"%d %d %lf %lf",&x,&y,&w,&h)==4)
    {
      printf("Found %s /MediaBox x=%d y=%d width=%f height=%f\n",type,x,y,w,h);
    }
  };

  const std::string streamStart = "stream\n";
  const std::string streamEnd = "\nendstream";
  size_t l = contents.length();
  size_t i=0;
  while (i<l)
  {
    if (contents[i]=='s' && strncmp(&contents[i],streamStart.c_str(),streamStart.length())==0)
         // compressed stream start
    {
      int col=0;
      i+=streamStart.length();
      size_t start=i;
      DBG(("---- start stream at offset %08x\n",(int)i));
      while (i<l)
      {
        if (contents[i]=='\n' && strncmp(&contents[i],streamEnd.c_str(),streamEnd.length())==0)
        {
          DBG(("\n---- end stream at offset %08x\n",(int)i));
          std::vector<char> decompressBuf;
          int ret = infate_buffer(&contents[start],i-start,decompressBuf);
          if (ret==Z_OK)
          {
            std::string s(decompressBuf.begin(), decompressBuf.end());
            DBG(("decompressed_data=[[[\n%s\n]]]\n",s.c_str()));
            size_t idx = s.find(mediaBox);
            if (idx!=std::string::npos)
            {
              showMediaBox(s.c_str()+idx,"compressed");
              i=l; // end outer loop
              break;
            }
          }
          else
          {
            printf("Error decoding buffer: ret=%d\n",ret);
          }
          i+=streamEnd.length();
          break;
        }
        else
        {
          if (col>16) { col=0; DBG(("\n%08x: ",(int)i)); }
          DBG(("%02x ",(unsigned char)contents[i]));
          col++;
          i++;
        }
      }
    }
    else if (contents[i]=='/' && strncmp(&contents[i],mediaBox.c_str(),mediaBox.length())==0)
    {
      showMediaBox(&contents[i],"uncompressed");
      break;
    }
    else // continue with next char
    {
      i++;
    }
  }
};
```

**Comment by doxygen** [comment]
I found a header only implementation to decompress the compressed part of the PDF and integrated that into doxygen. Can you please check if this works for you? (I don't have a dot version that uses cairo 1.17.6 myself)

**Comment by albert-github** [comment]
Hallo Dimitri,

Ik probeerde even deze patch met de good old 2017 Windows 32 en 64 compiler
en ook bij de 64 bit 2019 compiler krijg een aantal waarschuwingen (zie ook
op GitHub Actions):
[ 47%] Building CXX object src/CMakeFiles/doxymain.dir/dotrunner.cpp.obj
dotrunner.cpp
...\doxygen\TinyDeflate\gunzip.hh(975): warning C4244: 'initializing':
conversion from 'uint_least64_t' to 'uint_least16_t', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(1164): note: see reference to function
template instantiation 'int
gunzip_ns::Gunzip<1,DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>&,gunzip_ns::DeflateOutputDispatch::<lambda_19544df43fd00966f43aea6cf3241054>&,gunzip_ns::DeflateOutputDispatch::<lambda_7cd9f21417fa07d9fff4493ec2f64d25>&,_Ty>(InputFunctor,OutputFunctor,WindowFunctor,BacktrackFunctor
&&)' being compiled
        with
        [
            _Ty=gunzip_ns::dummy,

InputFunctor=DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>
&,

OutputFunctor=gunzip_ns::DeflateOutputDispatch::<lambda_19544df43fd00966f43aea6cf3241054>
&,

WindowFunctor=gunzip_ns::DeflateOutputDispatch::<lambda_7cd9f21417fa07d9fff4493ec2f64d25>
&,
            BacktrackFunctor=gunzip_ns::dummy
        ]
...\doxygen\TinyDeflate\gunzip.hh(1234): note: see reference to function
template instantiation 'int
gunzip_ns::DeflateDispatchFinal<1,DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>&,gunzip_ns::DeflateOutputDispatch::<lambda_19544df43fd00966f43aea6cf3241054>&,gunzip_ns::DeflateOutputDispatch::<lambda_7cd9f21417fa07d9fff4493ec2f64d25>&,_Ty>(I,O,C,B
&&)' being compiled
        with
        [
            _Ty=gunzip_ns::dummy,

I=DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637> &,

O=gunzip_ns::DeflateOutputDispatch::<lambda_19544df43fd00966f43aea6cf3241054>
&,

C=gunzip_ns::DeflateOutputDispatch::<lambda_7cd9f21417fa07d9fff4493ec2f64d25>
&,
            B=gunzip_ns::dummy
        ]
...\doxygen\TinyDeflate\gunzip.hh(1353): note: see reference to function
template instantiation 'int
gunzip_ns::DeflateOutputDispatch<1,_Ty,DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>&,DotRunner::readBoundingBox::<lambda_c93c40d1943d4f3ffb61292e04bae3cb>&>(BtFun
&&,InFun,T1)' being compiled
        with
        [
            _Ty=gunzip_ns::dummy,
            BtFun=gunzip_ns::dummy,

InFun=DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>
&,

T1=DotRunner::readBoundingBox::<lambda_c93c40d1943d4f3ffb61292e04bae3cb> &
        ]
...\doxygen\TinyDeflate\gunzip.hh(1430): note: see reference to function
template instantiation 'int
gunzip_ns::DeflateInputDispatch<0,gunzip_ns::dummy,DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>&,DotRunner::readBoundingBox::<lambda_c93c40d1943d4f3ffb61292e04bae3cb>&,>(BtFun
&&,T1,T2)' being compiled
        with
        [
            BtFun=gunzip_ns::dummy,

T1=DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637> &,

T2=DotRunner::readBoundingBox::<lambda_c93c40d1943d4f3ffb61292e04bae3cb> &
        ]
...\doxygen\src\dotrunner.cpp(210): note: see reference to function
template instantiation 'int
Deflate<DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>&,DotRunner::readBoundingBox::<lambda_c93c40d1943d4f3ffb61292e04bae3cb>&>(DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>
&,DotRunner::readBoundingBox::<lambda_c93c40d1943d4f3ffb61292e04bae3cb> &)'
being compiled
...\doxygen\TinyDeflate\gunzip.hh(980): warning C4244: '=': conversion from
'uint_least64_t' to 'uint_least16_t', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(982): warning C4244: 'initializing':
conversion from 'uint_least64_t' to 'uint_fast16_t', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(997): warning C4244: '=': conversion from
'uint_least64_t' to 'uint_least16_t', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(1003): warning C4244: '=': conversion
from 'uint_least64_t' to 'uint_least16_t', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(764): warning C4242: 'initializing':
conversion from 'uint_least32_t' to 'uint_least8_t', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(1028): note: see reference to function
template instantiation 'auto
gunzip_ns::DeflateState<false>::DynTreeFunc<true,DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>&,_Ty>(InputFunctor,uint_fast16_t,BacktrackFunctor
&&,bool)' being compiled
        with
        [
            _Ty=gunzip_ns::dummy,

InputFunctor=DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>
&,
            BacktrackFunctor=gunzip_ns::dummy
        ]
...\doxygen\TinyDeflate\gunzip.hh(771): warning C4244: '=': conversion from
'uint_least64_t' to 'uint_least32_t', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(1042): warning C4244: 'initializing':
conversion from 'uint_least64_t' to 'uint_least32_t', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(1051): warning C4244: 'initializing':
conversion from 'uint_least64_t' to 'unsigned char', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(1068): warning C4242: 'initializing':
conversion from 'uint_least32_t' to 'uint_least16_t', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(1074): warning C4244: 'argument':
conversion from 'uint_least16_t' to 'unsigned char', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(1079): warning C4244: 'initializing':
conversion from 'uint_least64_t' to 'uint_least16_t', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(1079): warning C4242: '+=': conversion
from 'unsigned int' to 'uint_least16_t', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(1080): warning C4242: 'initializing':
conversion from 'uint_least32_t' to 'uint_least8_t', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(1081): warning C4244: 'initializing':
conversion from 'uint_least64_t' to 'uint_least32_t', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(663): warning C4242: '-=': conversion
from 'unsigned int' to 'uint_least8_t', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(975): note: see reference to function
template instantiation 'uint_least64_t
gunzip_ns::DeflateBitCache::GetBits<true,DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>&>(InputFunctor,unsigned
int)' being compiled
        with
        [

InputFunctor=DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>
&
        ]
...\doxygen\TinyDeflate\gunzip.hh(1164): note: see reference to function
template instantiation 'int
gunzip_ns::Gunzip<1,DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>&,gunzip_ns::DeflateOutputDispatch::<lambda_19544df43fd00966f43aea6cf3241054>&,gunzip_ns::DeflateOutputDispatch::<lambda_7cd9f21417fa07d9fff4493ec2f64d25>&,_Ty>(InputFunctor,OutputFunctor,WindowFunctor,BacktrackFunctor
&&)' being compiled
        with
        [
            _Ty=gunzip_ns::dummy,

InputFunctor=DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>
&,

OutputFunctor=gunzip_ns::DeflateOutputDispatch::<lambda_19544df43fd00966f43aea6cf3241054>
&,

WindowFunctor=gunzip_ns::DeflateOutputDispatch::<lambda_7cd9f21417fa07d9fff4493ec2f64d25>
&,
            BacktrackFunctor=gunzip_ns::dummy
        ]
...\doxygen\TinyDeflate\gunzip.hh(325): warning C4242: 'argument':
conversion from 'unsigned int' to 'unsigned char', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(1026): note: see reference to function
template instantiation 'bool
gunzip_ns::CreateHuffmanTree<true,47,6,gunzip_ns::Gunzip::<lambda_ff7377c4fd061bdfa99818053d47ba19>&>(const
char *,gunzip_ns::RandomAccessArray<false,47,6> &,unsigned
int,LengthFunctor) noexcept' being compiled
        with
        [

LengthFunctor=gunzip_ns::Gunzip::<lambda_ff7377c4fd061bdfa99818053d47ba19> &
        ]
...\doxygen\TinyDeflate\gunzip.hh(336): warning C4242: 'argument':
conversion from 'unsigned int' to 'unsigned char', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(359): warning C4242: 'argument':
conversion from 'unsigned int' to 'unsigned char', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(705): warning C4805: '|': unsafe mix of
type 'unsigned int' and type 'bool' in operation
...\doxygen\TinyDeflate\gunzip.hh(762): note: see reference to function
template instantiation 'uint_least32_t
gunzip_ns::DeflateBitCache::HuffRead<true,DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>&,47,6>(InputFunctor,gunzip_ns::RandomAccessArray<false,47,6>
&)' being compiled
        with
        [

InputFunctor=DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>
&
        ]
...\doxygen\TinyDeflate\gunzip.hh(1028): note: see reference to function
template instantiation
'gunzip_ns::DeflateState<false>::DynTreeFunc::<lambda_eb374c7801a80c9492ce85405d8fe3d7>
gunzip_ns::DeflateState<false>::DynTreeFunc<true,DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>&,_Ty>(InputFunctor,uint_fast16_t,BacktrackFunctor
&&,bool)' being compiled
        with
        [
            _Ty=gunzip_ns::dummy,

InputFunctor=DotRunner::readBoundingBox::<lambda_92f057b4e6eab61f28efdbcb37a19637>
&,
            BacktrackFunctor=gunzip_ns::dummy
        ]
...\doxygen\TinyDeflate\gunzip.hh(325): warning C4242: 'argument':
conversion from 'unsigned int' to 'unsigned short', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(1029): note: see reference to function
template instantiation 'bool
gunzip_ns::CreateHuffmanTree<true,303,9,gunzip_ns::DeflateState<false>::DynTreeFunc::<lambda_eb374c7801a80c9492ce85405d8fe3d7>&>(const
char *,gunzip_ns::RandomAccessArray<false,303,9> &,unsigned
int,LengthFunctor) noexcept' being compiled
        with
        [

LengthFunctor=gunzip_ns::DeflateState<false>::DynTreeFunc::<lambda_eb374c7801a80c9492ce85405d8fe3d7>
&
        ]
...\doxygen\TinyDeflate\gunzip.hh(336): warning C4242: 'argument':
conversion from 'unsigned int' to 'unsigned short', possible loss of data
...\doxygen\TinyDeflate\gunzip.hh(359): warning C4242: 'argument':
conversion from 'unsigned int' to 'unsigned short', possible loss of data

Ik denk iets om nog even naar te kijken.

Onder Cygwin krijg ik geen waarschuwingen.

Groeten,

Albert

**Comment by uleysky** [comment]
Neither the program nor the doxygen is working. I am attaching one of the problematic files.
[comdefs_8h__incl.pdf](https://github.com/doxygen/doxygen/files/10349450/comdefs_8h__incl.pdf)

**Comment by computerix** [comment]
to @uleysky :
Works for me with escape-quoted font names.
Thanks!
(worked without quotes in earlier versions of doxygen?)

**Comment by uleysky** [comment]
> to @uleysky : Works for me with escape-quoted font names. Thanks! (worked without quotes in earlier versions of doxygen?)
This is a recent addition to the doxygen. Before that, there were DOT_FONTNAME and DOT_FONTSIZE variables that were properly quoted in the dot file. They have been replaced with new variables to better control the appearance of graphs. But in the default values, they forgot to put quotes around the string values.

**Comment by doxygen** [comment]
@uleysky The detection of flate encoded streams was too simplistic, causing false detections. Please test again with the latest commit.

**Comment by albert-github** [comment]
@uleysky 
The pushing back of the environment is indeed a difficult point especially for usage in sub processes.

Regarding the font name I don't get the point here as when I look at a `Doxyfile` with:
```
DOT_FONTNAME = "LiberationSans Regular"
```
doxygen sees this as (using `doxygen -x`):
```
DOT_COMMON_ATTR        = "fontname=\"LiberationSans Regular\",fontsize=10"
DOT_EDGE_ATTR          = "labelfontname=\"LiberationSans Regular\",labelfontsize=10"
```

In case of:
```
DOT_FONTNAME = "LiberationSans-Regular"
```
doxygen sees this as:
```
DOT_COMMON_ATTR        = "fontname=LiberationSans-Regular,fontsize=10"
DOT_EDGE_ATTR          = "labelfontname=LiberationSans-Regular,labelfontsize=10"
```

I did a small test (with the fontname LiberationSans-Regular) and indeed I got the message:
```
html/graph_legend.dot:1: error: Problems running dot: exit code=1, command='dot.exe', arguments='".../html/graph_legend.dot" -Tpng -o ".../html/graph_legend.png"'
```
further inspection gave (running `dot` directly on the file:
```
html/graph_legend.dot: syntax error in line 5 near '-'
```
placing double quotes around it did fix it, so this looks indeed like a bug (regression), I'll have to dive into it.

**Comment by albert-github** [comment]
Note: regarding the "LiberationSans-Regular" problem: I've just pushed a proposed patch, pull request #9773

**Comment by uleysky** [comment]
@doxygen, patch works now.

@albert-github, not working. Are you sure that the doxygen parses DOT_{COMMON,EDGE,NODE}_ATTR  into separate options and quote it? In any case, I don't consider this a bug. We simply pass some string to the dot, its correctness is up to the dot. You can specify in the documentation for the DOT_COMMON_ATTR that if the font name contains "-", then it must be enclosed in quotation marks.

**Comment by albert-github** [comment]
@uleysky
- did you check the proposed patch #9773?
  - if so can you please share your orinal Doxyfle
  - the output of `doxygen -x Doxyfile`

**Comment by uleysky** [comment]
doxygen -x
```
# Difference with default Doxyfile 1.9.7 (8129939c312e4b5060042fdb93bd071b7b133381*)
OUTPUT_DIRECTORY       = doxygen
OUTPUT_LANGUAGE        = Russian
INLINE_INHERITED_MEMB  = YES
FULL_PATH_NAMES        = NO
TOC_INCLUDE_HEADINGS   = 0
BUILTIN_STL_SUPPORT    = YES
IDL_PROPERTY_SUPPORT   = NO
NUM_PROC_THREADS       = 0
EXTRACT_PRIVATE        = YES
EXTRACT_STATIC         = YES
CASE_SENSE_NAMES       = YES
SORT_MEMBERS_CTORS_1ST = YES
SORT_GROUP_NAMES       = YES
WARN_NO_PARAMDOC       = YES
INPUT                  = .
RECURSIVE              = YES
EXCLUDE                = *.cpp
SOURCE_BROWSER         = YES
REFERENCED_BY_RELATION = YES
REFERENCES_RELATION    = YES
CLANG_ASSISTED_PARSING = YES
CLANG_OPTIONS          = -Wno-deprecated-declarations \
                         -std=c++20 \
                         -resource-dir=/usr/lib/llvm/15/bin/../../../../lib/clang/15.0.6
CLANG_DATABASE_PATH    = 0
GENERATE_TREEVIEW      = YES
FORMULA_FONTSIZE       = 12
USE_MATHJAX            = YES
MATHJAX_VERSION        = MathJax_3
MATHJAX_FORMAT         = chtml
MATHJAX_RELPATH        = https://cdn.jsdelivr.net/npm/mathjax@3
MATHJAX_EXTENSIONS     = ams
LATEX_CMD_NAME         = latex
EXTRA_PACKAGES         = amsmath \
                         amsfonts
LATEX_TIMESTAMP        = YES
MACRO_EXPANSION        = YES
EXPAND_ONLY_PREDEF     = YES
HIDE_UNDOC_RELATIONS   = NO
HAVE_DOT               = YES
DOT_COMMON_ATTR        = "fontname=Times-Roman,fontsize=10"
DOT_EDGE_ATTR          = "labelfontname=Times-Roman,labelfontsize=10"
TEMPLATE_RELATIONS     = YES
CALL_GRAPH             = YES
CALLER_GRAPH           = YES
DOT_IMAGE_FORMAT       = svg
INTERACTIVE_SVG        = YES
DOT_MULTI_TARGETS      = YES
```

**Comment by uleysky** [comment]
Yes, this lines was in original Doxyfile.
I checked translation from DOT_FONTNAME, it works.

**Comment by albert-github** [comment]
The version for `DOT_FONTNAME` has been integrated in master on GitHub, have to think about the other problem as indicated.

**Comment by albert-github** [comment]
Code (of pu;l request #9775) has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
